from flask import Flask, render_template, request, jsonify, send_file
from flask_mail import Mail, Message
from generator import generate_report_text, generate_pdf
import os
import json
from datetime import datetime

app = Flask(__name__)

app.config['MAIL_SERVER'] = 'smtp.gmail.com'
app.config['MAIL_PORT'] = 587
app.config['MAIL_USE_TLS'] = True
app.config['MAIL_USERNAME'] = 'rakshithad679@gmail.com'
app.config['MAIL_PASSWORD'] = 'echc rudb zayf fkya'
app.config['MAIL_DEFAULT_SENDER'] = 'rakshithad679@gmail.com'

mail = Mail(app)

HISTORY_FILE = 'history.json'

def load_history():
    if os.path.exists(HISTORY_FILE):
        with open(HISTORY_FILE, 'r') as f:
            return json.load(f)
    return []

def save_history(history):
    with open(HISTORY_FILE, 'w') as f:
        json.dump(history, f, indent=2)

@app.route("/")
def home():
    return render_template("index.html")

@app.route("/generate", methods=["POST"])
def generate():
    try:
        data = request.get_json()
        report = generate_report_text(data)
        filename = f"report_{data.get('patient_name','patient').replace(' ','_')}.pdf"
        pdf_path = generate_pdf(report, filename)

        history = load_history()
        history_entry = {
            "id": len(history) + 1,
            "patient_name": report["patient_name"],
            "age": report["age"],
            "gender": report["gender"],
            "date": report["date"],
            "symptoms": report["symptoms"],
            "risks": report["risks"],
            "recommendations": report["recommendations"],
            "findings": report["findings"],
            "simple_risks": report["simple_risks"],
            "simple_recs": report["simple_recs"],
            "prescriptions": report["prescriptions"],
            "pdf_file": filename,
            "timestamp": datetime.now().strftime("%d/%m/%Y %H:%M")
        }
        history.append(history_entry)
        save_history(history)

        return jsonify({
            "success": True,
            "report": report,
            "pdf_file": filename
        })

    except Exception as e:
        return jsonify({"success": False, "error": str(e)})

@app.route("/download/<filename>")
def download(filename):
    path = os.path.join("outputs", filename)
    return send_file(path, as_attachment=True)

@app.route("/history", methods=["GET"])
def get_history():
    history = load_history()
    return jsonify({"success": True, "history": history})

@app.route("/history/<int:patient_id>", methods=["GET"])
def get_patient(patient_id):
    history = load_history()
    patient = next((p for p in history if p["id"] == patient_id), None)
    if patient:
        return jsonify({"success": True, "patient": patient})
    return jsonify({"success": False, "error": "Patient not found"})

@app.route("/history/<int:patient_id>", methods=["DELETE"])
def delete_patient(patient_id):
    history = load_history()
    history = [p for p in history if p["id"] != patient_id]
    save_history(history)
    return jsonify({"success": True})

@app.route("/send-email", methods=["POST"])
def send_email():
    try:
        data = request.get_json()
        recipient = data.get("email")
        pdf_file = data.get("pdf_file")
        patient_name = data.get("patient_name", "Patient")
        pdf_path = os.path.join("outputs", pdf_file)

        msg = Message(
            subject=f"Medical Report - {patient_name}",
            recipients=[recipient]
        )
        msg.body = f"""
Dear {patient_name},

Please find your medical report attached.

This report was generated by the Medical Report Generator system.

Important: This report is AI-generated for assistance purposes only.
It is not a substitute for professional medical advice.
Always consult a qualified doctor.

Regards,
Medical Report Generator
        """
        with open(pdf_path, 'rb') as f:
            msg.attach(
                filename=pdf_file,
                content_type="application/pdf",
                data=f.read()
            )

        mail.send(msg)
        return jsonify({"success": True})

    except Exception as e:
        return jsonify({"success": False, "error": str(e)})

if __name__ == "__main__":
    app.run(debug=True)